import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :kubeybilly, KubeybillyWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# No force_ssl: the release serves plain HTTP inside the cluster (the
# Alertmanager webhook and kubelet probes arrive over the pod network with no
# TLS-terminating proxy in front). TLS is the ingress/mesh operator's layer;
# forcing a redirect here would 301 every in-cluster caller.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
