defmodule Kubeybilly.Logbook do
  @moduledoc """
  Writes the human handoff: `log.md` in the incident's bundle directory.

  The logbook is the last artifact of an incident and the first thing
  the on-call human reads, so its factual sections (timeline, soundings,
  signature, decision, action and undo, verification, open questions)
  are generated purely from the structured record and the sealed
  manifest by `Kubeybilly.Logbook.Sections`. The optional narrative is
  the one model-written part, appended only when explicitly enabled and
  clearly marked as prose with zero authority (plan/02, Layer 3): if the
  advisor fails, the section is simply absent and the factual record
  stands complete without it.
  """

  alias Kubeybilly.Advisor
  alias Kubeybilly.Incident.Record
  alias Kubeybilly.Logbook.Sections

  @log_file "log.md"

  @doc """
  Generate and write `log.md` for a closed incident record.

  Reads the bundle manifest from the incident directory (missing or
  unreadable manifests are reported inside the log, not errors), writes
  the rendered markdown next to it, and returns `{:ok, markdown}`. The
  root defaults to `config :kubeybilly, :incidents_dir`; pass `:root` to
  override, as tests do. An open record is refused: a log written before
  the outcome is settled would lie by omission.
  """
  @spec generate(Record.t(), keyword()) ::
          {:ok, String.t()} | {:error, :record_open | File.posix()}
  def generate(record, opts \\ [])

  def generate(%Record{status: :closed} = record, opts) do
    dir = Path.join(root(opts), record.id)
    markdown = Sections.render(record, read_manifest(dir)) <> narrative(record)

    with :ok <- File.mkdir_p(dir),
         :ok <- File.write(Path.join(dir, @log_file), markdown) do
      {:ok, markdown}
    end
  end

  def generate(%Record{} = _record, _opts), do: {:error, :record_open}

  @doc "The on-disk path of an incident's logbook."
  @spec path(String.t(), keyword()) :: Path.t()
  def path(incident_id, opts \\ []) do
    Path.join([root(opts), incident_id, @log_file])
  end

  defp root(opts) do
    Keyword.get_lazy(opts, :root, fn ->
      Application.get_env(:kubeybilly, :incidents_dir, "incidents")
    end)
  end

  defp read_manifest(dir) do
    with {:ok, binary} <- File.read(Path.join(dir, "manifest.json")),
         {:ok, manifest} when is_map(manifest) <- Jason.decode(binary) do
      manifest
    else
      _missing_or_invalid -> nil
    end
  end

  # The narrative is opt-in (config :kubeybilly, :advisor_narrate) and
  # best-effort: any advisor error means the section is omitted entirely,
  # never retried into the factual record.
  defp narrative(record) do
    if Application.get_env(:kubeybilly, :advisor_narrate, false) do
      case Advisor.narrate(Record.to_map(record)) do
        {:ok, text} ->
          "\n## Narrative (advisor)\n\n" <>
            "This narrative was generated by a model. The sections above are " <>
            "the factual record; where they disagree, the sections above win.\n\n" <>
            String.trim_trailing(text) <> "\n"

        {:error, _reason} ->
          ""
      end
    else
      ""
    end
  end
end
